name: Push to Another Repository

on:
  push:
    branches:
      - main  # 根据需要调整源分支名称

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v2

    - name: Push to Target Repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
      with:
        source-directory: '.'  
        destination-github-username: 'xinkeji'  
        destination-repository-name: 'picx-images-hosting'  
        user-email: 840263997@qq.com  
        target-branch: master
